### ISSUE TITLE
copy paste issue

### ISSUE THREAD

**Issue by Devarth123** [AstroNvim/AstroNvim#553]
i am not highly sure this from astro nvim but when i try to to copy paste text from one window to the other it doesn't work  what i tried :
```"+y```
after selecting the text in visual mode
any solutions?

**Comment by mehalter** [comment]
Also one last question, if you do `nvim -u NONE` and try doing copy/paste again as you were trying to do in AstroNvim do you see the same behavior or does it work without our configuration?

**Comment by mehalter** [comment]
Just for clarification, we are setting `clipboard=unnammedplus` by default which makes all yanking go to the `+` register by default so yanking to the `+` register explicitly is unnecessary. It should just join the system clipboard and the normal yanking and pasting in Neovim. This can be reverted to the default Neovim behavior with this minimal `user/init.lua`:


```lua
return {
  options = {
    opt = {
      clipboard = "",
    }
  }
}
```

**Comment by Devarth123** [comment]
Hey i am running arch linux and i fixed this issue by installing ```xclip```
and thanks for ur suggestion

**Comment by PatMulligan** [comment]
hey! I've never really messed around with Nvim before... i'm running pop!_os and having the same issue of not being able to copy from my AstroNvim... I have `xclip` installed.

@mehalter you said this can be fixed with the `user/init.lua` you mentioned above... I've tried creating a `~/.config/nvim/lua/user/init.lua` with the following:
```
return {
  options = {
    opt = {
      clipboard = "",
    }
  }
}
```

Still no luck with copy/paste. If I run `nvim -u NONE` my copy/paste functions as expected

**Comment by mehalter** [comment]
@PatMulligan when you have no configuration when you do a normal yank like `yy` are you able to then paste that somewhere else? Also vice versa if you just do a normal copy from outside the terminal and do `p` does it paste from your system clipboard?

**Comment by PatMulligan** [comment]
if I run an instance of `nvim -u NONE`, and I do a yank, I can only paste within the nvim instance using `p`, not anywhere else.

If I do a normal copy from outside the nvim instance, and do a `p` it does not paste from the system clipboard

**Comment by mehalter** [comment]
@PatMulligan I meant with a base AstroNvim installation and no user specific configuration, not with `-u NONE`. Sorry for the confusion! Could you try with a fresh AstroNvim installation?

**Comment by flamendless** [comment]
Just to add here, previously right click work for pasting, now right click does a different highlight

**Comment by mehalter** [comment]
@flamendless this would be handled by your terminal emulator I would imagine. We have never done anything surrounding mouse bindings. Have you recently changed your terminal emulator configuration or moved to a new emulator? Right clicking to paste is *not* a provided out of the box feature of AstroNvim.

**Comment by flamendless** [comment]
I didn't change anything in my terminal lately. I only just updated my astrovim config to the latest branch 🤔

**Comment by PatMulligan** [comment]
okay, yes to both of your questions then! so it appears to be working as intended then.

one of the ways I've gotten used to copy pasting on Pop!_OS is that I am able to just select text and then the text that gets selected is able to be pasted with a mouse scroll click. 

This functionality doesn't work with AstroNvim, even though it does work if I do `nvim -u NONE`. Do you know if this functionality is related to the copy paste? For some reason, my computer is not recognizing that I'm highlighting text in an AstroNvim window like it does with any other. And just for clarity, this "highlight -> scroll click paste" seems to have it's own clipboard, i.e., it doesn't replace what's in the system clipboard that gets pasted with ctrl+v.

**Comment by mehalter** [comment]
I believe this is because we set `mouse = "a"` as a default option. Could you try holding shift while selecting and middle clicking? Check here:

https://stackoverflow.com/questions/4608161/copying-text-outside-of-vim-with-set-mouse-a-enabled

**Comment by flamendless** [comment]
> I believe this is because we set `mouse = "a"` as a default option. Could you try holding shift while selecting and middle clicking? Check here:
> 
> https://stackoverflow.com/questions/4608161/copying-text-outside-of-vim-with-set-mouse-a-enabled

Shift + middle click doesnt work but middle click only works

**Comment by PatMulligan** [comment]
> I believe this is because we set `mouse = "a"` as a default option. Could you try holding shift while selecting and middle clicking? Check here:
> 
> https://stackoverflow.com/questions/4608161/copying-text-outside-of-vim-with-set-mouse-a-enabled

that works! thanks a bunch @mehalter for the quick responses and the stackoverflow link too. Looking forward to playing around with this
